# Generated by Django 3.2 on 2021-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('cableRun', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=25)),
                ('zipCode', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_finish', models.DateField()),
                ('cleanup', models.BooleanField(default=False)),
                ('total_material', models.FloatField(default=0.0)),
                ('total_labor', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('cables_cost', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=80)),
                ('item_location', models.CharField(max_length=80)),
                ('item_name', models.CharField(max_length=30)),
                ('item_quanity', models.IntegerField()),
                ('item_labor_cost', models.FloatField(default=0.0)),
                ('item_cost', models.FloatField(default=0.0)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.installation')),
            ],
        ),
        migrations.CreateModel(
            name='AVComponents',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.item')),
                ('total', models.FloatField(default=0.0)),
            ],
            bases=('invoices.item',),
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.item')),
                ('total', models.FloatField(default=0.0)),
            ],
            bases=('invoices.item',),
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.item')),
                ('total', models.FloatField(default=0.0)),
            ],
            bases=('invoices.item',),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('mfg_warranty', models.IntegerField(default=2)),
                ('add_warranty', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.item')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.appraisal')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.proposal'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.installation')),
            ],
        ),
        migrations.AddField(
            model_name='appraisal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customer'),
        ),
    ]
